# Generated by Django 6.0.5 on 2026-05-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_code', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('level', models.IntegerField()),
                ('country_iso', models.CharField(default='MWI', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='admin_areas.adminarea')),
            ],
            options={
                'verbose_name': 'Admin Area',
                'verbose_name_plural': 'Admin Areas',
                'ordering': ['level', 'name'],
            },
        ),
    ]
