# Generated by Django 6.0.5 on 2026-05-07 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_areas', '0001_initial'),
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arctriggerevent',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_trigger_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodforecastimpact',
            name='admin_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flood_impacts', to='admin_areas.adminarea'),
        ),
        migrations.AddField(
            model_name='floodforecastimpact',
            name='forecast_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impacts', to='pipeline.floodforecastfile'),
        ),
        migrations.AddField(
            model_name='hdxdataset',
            name='loaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loaded_datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodforecastfile',
            name='ingestion_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forecast_files', to='pipeline.jbaingestionrun'),
        ),
        migrations.AddConstraint(
            model_name='arcrainfallobservation',
            constraint=models.UniqueConstraint(fields=('observation_date', 'admin_area'), name='unique_arc_obs_date_admin'),
        ),
        migrations.AddConstraint(
            model_name='floodforecastimpact',
            constraint=models.UniqueConstraint(fields=('forecast_issue_date', 'forecast_target_date', 'admin_area'), name='unique_impact_issue_target_admin'),
        ),
        migrations.AddConstraint(
            model_name='floodforecastfile',
            constraint=models.UniqueConstraint(fields=('forecast_issue_date', 'forecast_target_date'), name='unique_forecast_issue_target_date'),
        ),
    ]
