# Generated by Django 6.0.5 on 2026-06-08 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_rename_blob_url_fields_to_filefields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('rows_expected', models.IntegerField(blank=True, null=True)),
                ('rows_processed', models.IntegerField(blank=True, null=True)),
                ('source_csv', models.FileField(blank=True, null=True, upload_to='arc/csv/')),
                ('error_log', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ARC Ingestion Run',
                'verbose_name_plural': 'ARC Ingestion Runs',
                'ordering': ['-run_date'],
            },
        ),
        migrations.RemoveField(
            model_name='arcrainfallobservation',
            name='source_csv',
        ),
        migrations.AddField(
            model_name='arcrainfallobservation',
            name='ingestion_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='pipeline.arcingestionrun'),
        ),
    ]
