app:
  environment: PROD
  appTypeEnvName: "APP_TYPE"
  image:
    name: SET-BY-CICD-IMAGE
    tag: SET-BY-CICD-TAG
    imagePullPolicy: IfNotPresent

  ingress:
    enabled: true
    className:
    host:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "50m"

  redis:
    enabled: false

  postgresql:
    enabled: false
    fullnameOverride: "mrcs-postgresql"
    architecture: standalone
    auth:
      postgresPassword: ""
      username: ""
      password: ""
      database: "mrcs"
    primary:
      persistence:
        enabled: "true"
        storageClass: ""
        size: 2Gi

  minio:
    enabled: false
    disableWebUI: true
    mode: standalone
    fullnameOverride: mrcs-minio
    global:
      defaultStorageClass:
    apiIngress:
      enabled: true
      ingressClassName: nginx
      hostname: ""
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    auth:
      forceNewKeys: true
      rootUser: mrcs
      rootPassword: ""
    persistence:
      enabled: true
      size: 1Gi
    defaultBuckets: mrcs-static,mrcs-media
    provisioning:
      enabled: true
      resourcesPreset: "nano"
      cleanupAfterFinished:
        enabled: true
      extraCommands:
        - "mc anonymous set download provisioning/mrcs-static"
        - "mc anonymous set download provisioning/mrcs-media"

  api:
    enabled: true
    replicaCount: 1
    containerPort: 80
    command: ["misc/prod/run_web.sh"]
    resources:
      requests:
        cpu: "0.3"
        memory: 0.4Gi
      limits:
        cpu: "0.5"
        memory: 1Gi

  worker:
    enabled: false
    beat:
      enabled: false
      command: ["celery", "-A", "main", "beat", "-l", "INFO"]
      resources:
        requests:
          cpu: "0.1"
          memory: 0.5Gi
        limits:
          cpu: "1"
          memory: 1Gi
    queueCommandPrefix:
      - "celery"
      - "-A"
      - "main"
      - "worker"
      - "-l"
      - "INFO"
    queues:
      default:
        enabled: true
        replicaCount: 1
        celeryArgs:
          - "-Q"
          - "default"
          - "--concurrency"
          - "4"
          - "--max-tasks-per-child"
          - "10"


  argoHook:
    enabled: true
    resources:
      requests:
        cpu: "0.1"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    hooks:
      db-migrate:
        enabled: true
        hook: PostSync
        preserveHistory: true
        command: ["/bin/bash", "-c", "./manage.py wait_for_resources --db && ./manage.py migrate"]
      collect-static:
        enabled: true
        hook: PostSync
        command: ["/bin/bash", "-c", "./manage.py wait_for_resources --minio && ./manage.py collectstatic --noinput"]


  env:
    APP_RELEASE: "{{ $.Values.image.tag }}"
    APP_ENVIRONMENT: "{{ $.Values.environment }}"
    DJANGO_DEBUG: "false"
    # AWS
    AWS_S3_ENABLED: "false"
    # App Domain
    APP_TYPE: "WEB"
    APP_DOMAIN: "{{ required \".app.env.APP_DOMAIN\" nil }}"
    FRONTEND_DOMAIN: "{{ required \".app.env.FRONTEND_DOMAIN\" nil }}"
    SESSION_COOKIE_DOMAIN: "{{ required \".app.env.SESSION_COOKIE_DOMAIN\" nil }}"
    CSRF_COOKIE_DOMAIN: "{{ required \".app.env.CSRF_COOKIE_DOMAIN\" nil }}"
    # Sentry
    SENTRY_ENABLED: "false"
    SENTRY_TRACES_SAMPLE_RATE: "0.2"
    SENTRY_PROFILE_SAMPLE_RATE: "0.2"

  secrets:
    DJANGO_SECRET_KEY: "{{ required \".Values.secrets.DJANGO_SECRET_KEY\" nil }}"
    # sentry
    SENTRY_DSN: "{{ required \".app.secrets.SENTRY_DSN\" nil }}"
