# Generated by Django 6.0.5 on 2026-05-07 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='trigger_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_logs', to='pipeline.arctriggerevent'),
        ),
    ]
